### ISSUE TITLE
PocketMine Fails to Correctly Compile PHP for Raspbian OS on Raspberry Pi

### ISSUE THREAD

**Issue by jingz2007** [PocketMine/php-build-scripts#11]
I know exactly how to fix the issue and have tested out the fix but it is not a change I can do on a github fork and pull request it. The initial install script needs to detect if the OS is a version of Raspbian and if it is it needs to make a folder called bin in the pocket mine installation location and extract the file PocketMine-MP.php from http://sourceforge.net/projects/pocketmine/files/builds/PHP_5.6.4_ARM_Raspbian_hard.tar.gz/download. Next, the installer needs to run the command chmod 0755 bin/php. It would probably be preferable to upload the php build for raspbian to your own site/file server instead of depending on source forge. Also, the link I included is not a direct download but a mirror download thing.

**Comment by Intyre** [comment]
Fixed: #14
