### ISSUE TITLE
Library Issues

### ISSUE THREAD

**Issue by JustOneMoreBlock** [PocketMine/php-build-scripts#12]
Hello,

Just noting for anyone else has problems. I may attempt to compile from source.

error while loading shared libraries: libyaml-0.so.2: cannot open shared object file: No such file or directory

error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory

LIBPNG_VERSION="1.6.17" (Noticed there is a 1.6.18 build out and a patch.)

Tested Information:
CentOS 6 x64
Builds: #144 and #146 for PHP7
http://jenkins.pocketmine.net/job/PHP-PocketMine-Linux/

Regards,
Cory

**Comment by shoghicp** [comment]
The builds provided are for Ubuntu/Debian, if you use the installer these are tested and the compile script is called automatically.
