### ISSUE TITLE
Some issues when compiling php7

### ISSUE THREAD

**Issue by iVertx** [PocketMine/php-build-scripts#13]
I'm getting some issues when compiling php7 in some architetures, In my tests I compiled for armv7 and 64bit

And i got errors in some of my compilation attempts...

ARMv7:
Ubuntu 15.10 dev, 12.10 & Fedora 21 ended up with the exact same error:

gcc is /usr/bin/gcc
gcc: error: unrecognized command line option ‘-m32’
rm: cannot remove ‘test’: No such file or directory
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.

Pretty sure the compiler isn't recognizing that the machine is ARMv7 and are trying to build in 32bits...
And on Ubuntu 12.10 x86_64 sometimes i got issues when the compiler are checking "curl", but only happens on version 0_44_0 of curl, 0_41_0 works just fine. I don't know what exactly is that error on curl but i will update here when i get this error again, this issue has own life...

Just for reporting, feel free to close that, I will still updating that with the issues I got using the compiler on different plataforms and architetures... Maybe this can useful for doing php7 more acessible for production...

**Comment by shoghicp** [comment]
There is an armv7 target that you have to specify manually, but this may not work.

**Comment by iVertx** [comment]
Yes, isn't work, but cross-compiling from another plataform work as well...
The problem is just on "plataform detection" from compiler

**Comment by shoghicp** [comment]
If you pass the target (armv7) it won't try to detect and use the specified platform. Some examples of platforms are linux32, linux64, armv7, rpi, mac32, mac64, etc.

**Comment by iVertx** [comment]
ok, i realized that

Now I got the issue with curl 0_44_0 again, posting here the last lines from log for avoid spamming the first post:

    buildconf: running automake
    configure.ac:129: installing `./compile'
    configure.ac:182: installing `./config.guess'
    configure.ac:182: installing `./config.sub'
    configure.ac:129: installing `./install-sh'
    configure.ac:201: required file `./ltmain.sh' not found
    configure.ac:130: installing `./missing'
    docs/examples/Makefile.am: installing `./depcomp'
    src/Makefile.inc:112: variable `curl_SOURCES' is defined but no program or
    src/Makefile.inc:112: library has `curl' as canonical name (possible typo)
    Makefile.am:151:   `src/Makefile.inc' included from here
    buildconf: automake command failed

This one happened now on Ubuntu 14.10 LTS x86_64...

**Comment by Tupsi** [comment]
I ran into the same problems trying to compile myself as the downloaded php through the installer is just throwing core dumps on my system (ubuntu 16 lts).
Any help appreciated.

The problem seems to be in the script itself. The "missing" ltmain.sh gets created, but NOT inside the same dir (./) but instead in ../../ for whatever reason. If I copy that script down into the curl folder a manual automake runs just fine.
