### ISSUE TITLE
Installation script not working on newer Raspberry pi(s) (+fix)

### ISSUE THREAD

**Issue by chtronche** [PocketMine/php-build-scripts#14]
This boils down to the platform detection being made with
grep -q BCM2708 /proc/cpuinfo
(approx line 300 in the script), while newer RPIs report BCM2709, hence it may be fixed by changing to grep -q BCM270[89]

**Comment by Intyre** [comment]
It recognizes my RPi2 but somehow can't download the PHP binary. Can you try it using this installer?  https://gist.githubusercontent.com/Intyre/f185b148074e2f5bdf85/raw/125f3389d2f2062edd34133cc493af5bc1e5b3f8/installer.sh

Just replace get.pocketmine.net with that url.
