### ISSUE TITLE
php7(stable) was released

### ISSUE THREAD

**Issue by Fer0c** [PocketMine/php-build-scripts#19]

**Comment by luca28pet** [comment]
I made a pull request for windows binaries 
(https://github.com/PocketMine/php-build-scripts/pull/18)

**Comment by Fer0c** [comment]
oh thx!. You can make pull request for Linux binaries?

**Comment by luca28pet** [comment]
No, unfortunately I haven't a Linux machine to do tests
Hopefully @shoghicp will do the rest of the work

**Comment by Fer0c** [comment]
I hope too

**Comment by Intyre** [comment]
Branch php7 is updated for 7.0.1. 1a4a0d1ad1124bc2
