### ISSUE TITLE
Referenced libpng version now at different URL.

### ISSUE THREAD

**Issue by rduplain** [PocketMine/php-build-scripts#21]
The `compile.sh` script references `LIBPNG_VERSION="1.6.17"`. As of this writing, the latest version of libpng is 1.6.20 and it appears that the referenced sourceforge URL has moved the 1.6.17 release to a different URL than the one listed in `compile.sh`.

The resulting behavior, the build stops abruptly with:

    [libpng] downloading 1.6.17...

The install log indicates that the downloaded file is not a valid archive, which happens because the URL is returning a web page instead of an archive.

    gzip: stdin: unexpected end of file

The simple fix is to keep the reference to 1.6.17 and update the URL coded in the build to refer to the [new location at sourceforge](http://sourceforge.net/projects/libpng/files/libpng16/older-releases/1.6.17/) (which is in an "older-releases" folder now and is presumably a stable URL. If you update `LIBPNG_VERSION="1.6.20"`, then this issue will happen again when 1.6.20 moves to older releases.

By the way, this pattern of downloading is a leap of faith and will always be fragile. A more reliable approach would be to verify checksums and report problems with the download. Also inconvenient, the build script has no way to continue where it left off.

**Comment by Intyre** [comment]
9a566c978e :+1:
