### ISSUE TITLE
jenkins.sh may delete data

### ISSUE THREAD

**Issue by jazzwhistle** [PocketMine/php-build-scripts#22]
I was playing around with these scripts, got as far as a missing Weakref error and then ran ./jenkins.sh only to have my entire Home folder deleted... luckily it's a brand new setup so no data was lost. Maybe this line is to blame?!

rm -rf $WORKSPACE/*

**Comment by Intyre** [comment]
Read the script before executing it. ``jenkins.sh`` is used by Jenkins to compile all PHP binaries. DON'T use it yourself.
