### ISSUE TITLE
don't run jenkins.sh on it's own

### ISSUE THREAD

**Issue by zychrias** [PocketMine/php-build-scripts#27]
Note to others...don't run 'jenkins.sh' on it's own as is.  wiped my entire user directory structure and then some before I cancelled out.  Now to do a full OS reinstall...

**Comment by PEMapModder** [comment]
Is this an issue at all? This is not a forum.

**Comment by davidthedopest** [comment]
I think it doesn't specifies where "$WORKSPACE/*" is, it wiped my computer too aha.

**Comment by benyanke** [comment]
Yeah, that's an issue +PeMapModder. It happened to me too. This really needs to be fixed.

**Comment by ZedCee** [comment]
I officially call it the "rm -rf incident"
This is an issue, it overrides coreutil (rm) restrictions.
