### ISSUE TITLE
error when running the sercer

### ISSUE THREAD

**Issue by ARKopp** [PocketMine/php-build-scripts#30]
Hi copied the php7 bin into the directory and I get these error messages. Almost tried all php7 bins. 

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///Users/andy/Dropbox/MyProjects/Minecraft/pocketmine/PocketMine-MP.phar/src/pocketmine/Server__64bit.php on line 80

**Comment by Zootsuitpenguin** [comment]
I too have a similar issue- on iOS: 

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///Users/andrewgreen/Minecraft/PocketMine-MP.phar/src/pocketmine/Server.php on line 71

**Comment by PEMapModder** [comment]
@ARKopp you are using the correct PHP binaries, but the wrong PocketMine version.

**Comment by MitchTheAwesome** [comment]
which pocketmine are u suppose to be using then

**Comment by PEMapModder** [comment]
Use releases from the latest commit. Not the build \#1266 from www.pocketmine.net

https://bintray.com/pocketmine/PocketMine/PocketMine-MP-phar/view

**Comment by MitchTheAwesome** [comment]
Now I get this 

Couldn't find a valid PocketMine-MP installation

**Comment by PEMapModder** [comment]
You installed it wrongly...

**Comment by Anoche** [comment]
im still confused. which one are you supposte to be installing then?

**Comment by hai-nguyen-van** [comment]
I have the same problem with macOS. I retrieved the latest PHP version for macOS that is 7.0.3 and the latest version of PocketMine-MP 1.4.1 (build 980, API 1.11.0). Which version of macOS is then supposed to work ?
