### ISSUE TITLE
Float is a special float name

### ISSUE THREAD

**Issue by MitchTheAwesome** [PocketMine/php-build-scripts#31]
Hi

Could someone please help me!
I'm using a mac (el capitan) and I have setup the server but every time I run it I get the text Below!
I'm using php 7.0.3 downloaded at https://bintray.com/pocketmine/PocketMine/Unix-PHP-Binaries/7.0.3/view 
This is really annoying and would like a solution asap

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///Users/mitchellpescud/Desktop/PocketMine/PocketMine-MP.phar/src/pocketmine/Server.php on line 71

**Comment by PEMapModder** [comment]
Duplicate of #30
