### ISSUE TITLE
Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/pi/pocketmine/PocketMine-MP_1.4.1.phar/src/pocketmine/Server.php on line 71

### ISSUE THREAD

**Issue by curfew3749** [PocketMine/php-build-scripts#39]
First time trying to get pocket mine running on a raspberry pi 3 b.  I have Java 7.0.6 installed.  I downloaded pocket mine by running wget -q -O - https://get.pocketmine.net/ | bash.  If someone ne could lead me in the right direction, that would be great!

**Comment by curfew3749** [comment]
I also downloaded a phar file by running, wget https://github.com/PocketMine/PocketMine-MP/releases/download/1.4.1/PocketMine-MP_1.4.1.phar.

the contents of my start.sh file look like this,

`

#!/bin/bash
DIR="$(cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
cd "$DIR"

DO_LOOP="no"

while getopts "p:f:l" OPTION 2> /dev/null; do
	case ${OPTION} in
		p)
			PHP_BINARY="$OPTARG"
			;;
		f)
			POCKETMINE_FILE="$OPTARG"
			;;
		l)
			DO_LOOP="yes"
			;;
		\?)
			break
			;;
	esac
done

if [ "$PHP_BINARY" == "" ]; then
	if [ -f ./bin/php7/bin/php ]; then
		export PHPRC=""
		PHP_BINARY="./bin/php7/bin/php"
	elif [ type php 2>/dev/null ]; then
		PHP_BINARY=$(type -p php)
	else
		echo "Couldn't find a working PHP 7 binary, please use the installer."
		exit 1
	fi
fi

if [ "$POCKETMINE_FILE" == "" ]; then
	if [ -f ./PocketMine-MP.phar ]; then
		POCKETMINE_FILE="./PocketMine-MP.phar"
	elif [ -f ./src/pocketmine/PocketMine.php ]; then
		POCKETMINE_FILE="./src/pocketmine/PocketMine.php"
	else
		echo "Couldn't find a valid PocketMine-MP installation"
		exit 1
	fi
fi

LOOPS=0

set +e
while [ "$LOOPS" -eq 0 ] || [ "$DO_LOOP" == "yes" ]; do
	if [ "$DO_LOOP" == "yes" ]; then
		"$PHP_BINARY" "$POCKETMINE_FILE" $@
	else
		exec "$PHP_BINARY" "$POCKETMINE_FILE" $@
	fi
	((LOOPS++))
done

if [ ${LOOPS} -gt 1 ]; then
	echo "Restarted $LOOPS times"
fi

`

**Comment by curfew3749** [comment]
files currently in my pocket mine directory...

<img width="556" alt="screen shot 2017-07-02 at 2 58 25 am" src="https://user-images.githubusercontent.com/9036885/27767848-6deb1b80-5ed2-11e7-957c-db77171c36bc.png">

**Comment by wnabil** [comment]
hmmm same here but it seems the 1.4.1 not compatible with php7
rename the folder name from php5 to php7 inside bin folder fixes the problem

**Comment by sean-perryman** [comment]
Alternatively, I change the references to PHP7 in the start.sh file to PHP5. Problem solved!
