### ISSUE TITLE
Pocketmine wont run

### ISSUE THREAD

**Issue by MCButterMonster** [PocketMine/php-build-scripts#41]
I installed pocketmine on my raspberry pi B+ but I get this error,

pi@FracturedPrison:~/server$ sudo ./start.sh

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/pi/server/PocketMine-MP.phar/src/pocketmine/Server__32bit.php on line 80

Any help is appreciated!

**Comment by ghost** [comment]
use pmmp

**Comment by redchuck** [comment]
pmmp has dropped support for Raspberry Pi unless you do something pretty nonstandard to get a 64 bit OS.  Try using http://nukkit.io/ instead.
