### ISSUE TITLE
compile.sh fails while compiling zlib on 32 bit Debian 7.8

### ISSUE THREAD

**Issue by kingofnerds** [PocketMine/php-build-scripts#8]
When trying to compile php on 32bit Debian 7.8, it errors out when compiling zlib. Removing the environment variable for ranlib seems to fix the problem. even if I point the environment variable directly at the installed ranlib in /usr/bin/ranlib, it still errors out, but when I unset the $RANLIB variable, it compiles successfully from my shell, but still fails when making the same change in compile.sh.

**Comment by kingofnerds** [comment]
To clarify, from my regular logged in shell, I cd to install_data/zlib run the same ./configure string being used by the compile.sh then run the same make -j 1 command used by compile.sh, and zlib compiles successfully

I also tried setting RANLIB to /usr/bin/gcc-ranlib, an empty string, and /usr/bin/ranlib and in each instance the compile of zlib errored out. I use the 'unset RANLIB' command in the compile.sh script directly before the configure and make, and it still fails.

If there is any other information I can provide, please let me know.

Thanks

**Comment by shoghicp** [comment]
Can you provide the config.log on the zlib directory after it fails?

**Comment by kingofnerds** [comment]
http://pastebin.com/raw.php?i=1TWsprXz (configure.log)
http://pastebin.com/raw.php?i=v9XPpFiE (install.log)

**Comment by kingofnerds** [comment]
I just tried it again and it works now. changes to zlib or some other compile related place seems to have fixed the problem.

Thanks!
