### ISSUE TITLE
[Linux Install] Errors

### ISSUE THREAD

**Issue by Rondoozle** [PocketMine/php-build-scripts#9]
Trying to install PocketMine-MP on Godaddy Linux server using PuTTY through SSH. 

 wget -q -O - http://get.pocketmine.net/ | bash

[*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[*] This stable build was released on Tue Mar 17 10:00:47 MST 2015
[+] The build was signed, will check signature
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar... done!
[*] Checking signature of PocketMine-MP.phar
gpg: Signature made Tue Mar 17 10:16:17 2015 MST using RSA key ID A7837F89
gpg: requesting key A7837F89 from hkp server pgp.mit.edu
gpg: unable to execute program `/usr/libexec/gpg2keys_curl': No such file or directory
gpg: no handler for keyserver scheme `hkp'
gpg: Can't check signature: No public key
[!] Invalid signature! Please check for file corruption or a wrongly imported public key (signed by 20D377AFC3F7535B3261AA4DCF48E7E52280B75B)

Using installer:
 curl -sL \
> https://raw.githubusercontent.com/PocketMine/php-build-scripts/master/installer.sh \
>  | bash -s - -v development
[*] Found PocketMine-MP Final_1.5dev (build 1232) using API 1.12.0
[*] This development build was released on Mon Jun  8 06:50:29 MST 2015
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.5dev-1232 phar... done!
[3/3] Obtaining PHP: detecting if build is available...
[3/3] Linux 64-bit PHP build available, downloading PHP_5.6.8_x86-64_Linux.tar.gz... checking... invalid build detected, please upgrade your OS
[3/3] no build found, compiling PHP automatically
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependecies
[INFO] Compiling for current machine using 64-bit
[PHP] downloading 5.6.9... done!
[zlib] downloading 1.2.8... checking... compiling... username@domain [~/PocketMine-MP]$ 

Install.log:
Tue Jun  9 00:53:51 MST 2015
Linux a2plcpnl0188.prod.iad2.secureserver.net 2.6.32-531.29.2.lve1.3.11.1.el6.x86_64 #1 SMP Thu Dec 18 06:49:17 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
make is /usr/bin/make
autoconf is /usr/bin/autoconf
automake is /usr/bin/automake
libtool is /usr/bin/libtool
m4 is /usr/bin/m4
wget is /usr/bin/wget
getconf is /usr/bin/getconf
gzip is /bin/gzip
bzip2 is /usr/bin/bzip2
wget is /usr/bin/wget
gcc is /usr/bin/gcc
Checking for shared library support...
Building shared library libz.so.1.2.8 with gcc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I. -c -o example.o test/example.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o adler32.o adler32.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o crc32.o crc32.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o deflate.o deflate.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o infback.o infback.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o inffast.o inffast.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o inflate.o inflate.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o inftrees.o inftrees.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o trees.o trees.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o zutil.o zutil.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o compress.o compress.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o uncompr.o uncompr.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzclose.o gzclose.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzlib.o gzlib.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzread.o gzread.c
gcc -O2 -fPIC -march=native -mtune=native -fno-gcse -m64   -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN   -c -o gzwrite.o gzwrite.c
gcc-ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
make: gcc-ar: Command not found
make: *** [libz.a] Error 127

**Comment by shoghicp** [comment]
Try the second one again.

**Comment by Rondoozle** [comment]
It worked, Thanks!
